/**
 * @file      lorawan_commissioning.h
 *
 * @brief     End device commissioning parameters
 *
 * The Clear BSD License
 * Copyright Semtech Corporation 2024. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted (subject to the limitations in the disclaimer
 * below) provided that the following conditions are met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above copyright
 *       notice, this list of conditions and the following disclaimer in the
 *       documentation and/or other materials provided with the distribution.
 *     * Neither the name of the Semtech corporation nor the
 *       names of its contributors may be used to endorse or promote products
 *       derived from this software without specific prior written permission.
 *
 * NO EXPRESS OR IMPLIED LICENSES TO ANY PARTY'S PATENT RIGHTS ARE GRANTED BY
 * THIS LICENSE. THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
 * CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT
 * NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
 * PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL SEMTECH CORPORATION BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 */

#ifndef LORAWAN_COMMISSIONING_H
#define LORAWAN_COMMISSIONING_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * -----------------------------------------------------------------------------
 * --- DEPENDENCIES ------------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC MACROS -----------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC CONSTANTS --------------------------------------------------------
 */

/**
 * @brief Use internal credential
 * @remark By setting true the credentials defined in this document will not be used
 */
#ifndef USE_LR11XX_CREDENTIALS
#define USE_LR11XX_CREDENTIALS false
#endif  // USE_LR11XX_CREDENTIALS

/**
 * @brief IEEE Organizationally Unique Identifier ( OUI ) (big endian)
 * @remark This is unique to a company or organization
 */
#define IEEE_OUI 0x00, 0x00, 0x00

/**
 * @brief Device IEEE EUI (big endian)
 *
 * @remark In this application the value is automatically generated by calling
 *         lr1110_modem_get_dev_eui function
 */

#ifndef LORAWAN_DEVICE_EUI
#define LORAWAN_DEVICE_EUI                     \
    {                                          \
        IEEE_OUI, 0x00, 0x00, 0x00, 0x00, 0x12 \
    }
#endif  // LORAWAN_DEVICE_EUI
#define LORAWAN_DEVICE_EUI_LEN 8

/**
 * @brief App/Join server IEEE EUI (big endian)
 */
#ifndef LORAWAN_JOIN_EUI
#define LORAWAN_JOIN_EUI                               \
    {                                                  \
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x34 \
    }
#endif  // LORAWAN_JOIN_EUI
#define LORAWAN_JOIN_EUI_LEN 8

/**
 * @brief loRaWAN Network Key (big endian)
 */
#ifndef LORAWAN_NWK_KEY
#define LORAWAN_NWK_KEY                                                                                \
    {                                                                                                  \
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x56 \
    }
#endif  // LORAWAN_NWK_KEY
#define LORAWAN_NWK_KEY_LEN 16

/**
 * @brief loRaWAN Application Key (big endian)
 */
#ifndef LORAWAN_APP_KEY
#define LORAWAN_APP_KEY                                                                                \
    {                                                                                                  \
        0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x78 \
    }
#endif  // LORAWAN_APP_KEY
#define LORAWAN_APP_KEY_LEN 16

/**
 * @brief ABP Device Address
 */
#ifndef LORAWAN_ABP_DEV_ADDR
#define LORAWAN_ABP_DEV_ADDR                                                   \
    {                                                                          \
        0x01, 0x02, 0x03, 0x04                        \
    }
#endif  // LORAWAN_ABP_DEV_ADDR

/**
 * @brief ABP Network Session Key (big endian)
 */
#ifndef LORAWAN_ABP_NWK_SKEY
#define LORAWAN_ABP_NWK_SKEY                                                                           \
    {                                                                                                  \
        0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10 \
    }
#endif  // LORAWAN_ABP_NWK_SKEY

/**
 * @brief ABP Application Session Key (big endian)
 */
#ifndef LORAWAN_ABP_APP_SKEY
#define LORAWAN_ABP_APP_SKEY                                                                           \
    {                                                                                                  \
        0x10, 0x0F, 0x0E, 0x0D, 0x0C, 0x0B, 0x0A, 0x09, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10 \
    }
#endif  // LORAWAN_ABP_APP_SKEY

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC TYPES ------------------------------------------------------------
 */

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC FUNCTIONS PROTOTYPES ---------------------------------------------
 */

#ifdef __cplusplus
}
#endif

#endif  // LORAWAN_COMMISSIONING_H

/* --- EOF ------------------------------------------------------------------ */
